version: '3.8'

services:
  # app's container
  app:
    build:
      context: .
    container_name: flask_app
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend

  # dev db
  db:
    image: postgres:13
    container_name: flask_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  # for better visualisation
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"  # pgAdmin's port
    depends_on:
      - db
    networks:
      - backend

  # it's taking Dockerfile from .db_test. folder
  db_test:
    build:
      context: ./db_test/
    container_name: flask_db_test
    ports:
      - "5435:5432"
    env_file:
      - .env.test

    # Remember about different volumes for different db used in project
    volumes:
      - db_test_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:
  db_test_data:

networks:
  backend:
