name: Build Docker container for business_card_flask_app

on:
  push:
    branches:
      - BC-6

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # clone my code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      # set ups for login
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


        # building images for tests, and pushing them
      - name: Build and push flask_app image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: diiego300years/business_card_app:latest
          build-args: # Here we pass environment variables as build arguments
            FLASK_APP: ${{ secrets.FLASK_APP }}
            SQLALCHEMY_DATABASE_URI: ${{ secrets.TEST_DB_URI }}
            FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}

            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
            MAIL_PORT: ${{ secrets.MAIL_PORT }}
            FLASKY_MAIL_SENDER: ${{ secrets.FLASKY_MAIL_SENDER }}
            MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
            MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
            FLASKY_ADMIN: ${{ secrets.FLASKY_ADMIN }}
            FLASK_CONFIG: ${{ secrets.FLASK_CONFIG }}
            FLASK_APP_NAME: ${{ secrets.FLASK_APP_NAME }}



      - name: Build and push db_test image
        uses: docker/build-push-action@v4
        with:
          context: ./db_test
          push: true
          tags: diiego300years/db_test_business_card:latest
          build-args: # Here we pass environment variables as build arguments
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}


