name: Build Docker container for business_card_flask_app

on:
  push:
    branches:
      - BC-6

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # clone my code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push flask_app image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: diiego300years/business_card_app:latest

      - name: Build and push db_test image
        uses: docker/build-push-action@v4
        with:
          context: ./db_test
          push: true
          tags: diiego300years/db_test_business_card:latest
